### PR TITLE
Relax assertion on IW in OoO mux and connect ECC signals in the interconnect.

### PR DESCRIPTION
**Pull request by yvantor**

### CODE REVIEW

**Comment by FrancescoConti** [comment]
It needs to be rebased on the current `master`. The PR is currently on a version of HCI v2.0, not v2.1 (with several important fixes).

**Comment by yvantor** [comment]
I rebased and I see that what was merged into PULP cluster also incorporated other fixes from @micprog that were not merged. @FrancescoConti if OK for you, I would incorporate such changes in this PR, otherwise if you prefer I can open two different ones.

**Comment by yvantor** [comment]
As a proof of working I will use this branch into pulp_cluster.

**Comment by yvantor** [comment]
All good, have a look at [75](https://github.com/pulp-platform/pulp_cluster/pull/75).

**Review by FrancescoConti — APPROVED** [review]

**Pull request merged**
